site_name: Python kurs
site_url: https://fsteak.github.io/mkdocsmaterial/
repo_name: FSteak/mkdocsmaterial
repo_url: https://github.com/FSteak/mkdocsmaterial/
site_description: Python-kurs do'stim bilan yaratilgan bo'lib mkdocs-material ishlatilgan
nav:
  - Bosh sahifa:
    - index.md
    - 'Proekt Xaqida': 'about.md'
    - 'Litsenziya': 'LICENSE.md'
  - Boshlanishi:
    - getting-started/index.md
    - "Python-ni o'rnatish": "getting-started/installing-python.md"
    - "Termux": getting-started/termux.md
edit_uri: edit/master/docs/
extra:
  consent:
    title: Cookie consent
    description: >- 
      Biz sizni takroriy tashriflaringiz va sozlamalaringizni, va yanada bizning dokumentatsiyamizga va foydalano'vchi nima izlayotganini topish uchun yordam berish uchun cookie-fayllarini ishlatamiz.
      Sizning roziligingiz bilan, siz bizga dokumentatsiyamizni yahshiroq qilishga yordam berayotgan bolasiz.
  analytics:
    provider: google
    property: G-XVNDRHN83B
    feedback:
      title: Bu sahifa yordam berdimi?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Ha, bu sahifa yordam berdi.
          data: 1
          note: >-
            Malumotingiz uchun raxmat!
        - icon: material/emoticon-sad-outline
          name: Bu sahifani yahshiroq qilsa boladi.
          data: 0
          note: >- 
            Malumotingiz uchun raxmat! Bizning saytimizga yo'rdam berish uchun <a href="malto://boblox@duck.com" target="_blank" rel="noopener">elektron po'chtamizga</a> jonatsangiz boladi.
  homepage: /
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ITProggerUZ
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
    view: material/eye
    edit: material/pencil
    logo: simple/materialformkdocs
  # custom_dir: overrides
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Qorong'i rejimiga o'tish
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Yoriq rejimiga o'tish
  language: uz
  features:
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - toc.follow
    - navigation.top
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
plugins:
  - group:
      enabled: !ENV CI
      plugins:
        - glightbox
        - social:
            cards: true
        - git-revision-date-localized:
            enable_creation_date: true
        - git-committers:
            repository: FSteak/mkdocsmaterial
            branch: master
        - git-authors:
            enabled: true
  - search
  - tags:
      tags: true
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - toc:
      anchorlink: true
      permalink: true
  - pymdownx.smartsymbols
copyright: Copyright &copy; 2024 FSteak
