
name: mkdocs deploy

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bomb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          spare-checkout: |
            docs
            includes
      - name: Configure Git Creds
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install "mkdocs-material[imaging]"
          pip install mkdocs-glightbox
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-revision-date-localized-plugin
      - name: Final step-Deploy
        run: CI=true mkdocs gh-deploy --force